apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: student-service
  namespace: staging
  labels:
    app: student-service
spec:
  selector:
    matchLabels:
      app: student-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
